apiVersion: apps/v1
kind: Deployment
metadata:
  name: indz-app
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: indz
  template:
    metadata:
      labels:
        app: indz
    spec:
      containers:
        - name: indz
          image: ghcr.io/OWNER/REPO:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
